[project]
name = "server"
version = "0.1.0"
description = "Rapid broker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "ruff>=0.14.0",
    "uvicorn>=0.38.0",
]
